name: Build MindTheGapps

on:
  workflow_dispatch:
    inputs:
      release:
        description: "Release"
        required: true
        default: false
        type: boolean

jobs:
  build:
    strategy:
      matrix:
        arch: ["arm", "arm64", "x86", "x86_64"]
        androidv: ["12.1.0", "13.0.0", "14.0.0"]
    name: Build ${{ matrix.androidv }}-${{ matrix.arch }}
    runs-on: ubuntu-latest
    steps:

      - name: Map Android Version to tree
        run: |
          declare -A ANDROID_VER_MAP=(["12.1.0"]="sigma" ["13.0.0"]="tau" ["14.0.0"]="upsilon")
          echo "ANDROIDV=${ANDROID_VER_MAP[${{ matrix.androidv }}]}" >> $GITHUB_ENV
          declare -A ANDROID_API_MAP=(["12.1.0"]=32 ["13.0.0"]=33 ["14.0.0"]=34)
          echo "ANDROID_API=${ANDROID_API_MAP[${{ matrix.androidv }}]}" >> $GITHUB_ENV

      - name: Clone repository
        run: |
          git config --global http.version HTTP/1.1
          git clone --depth=1 -b ${{ env.ANDROIDV }} https://gitlab.com/MindTheGapps/vendor_gapps.git/

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build
        working-directory: vendor_gapps
        run: |
          mkdir common/proprietary/product/overlay
          sed -i -e '/overlay/d' build/gapps.sh
          sed -i -e '/RROs/d' build/gapps.sh
          echo "Compiling RROs"
          export PATH="/usr/local/lib/android/sdk/build-tools/34.0.0:$PATH"
          cp build/sign/testkey.pk8 cert.pk8
          find overlay -maxdepth 1 -mindepth 1 -type d -print0 | while IFS= read -r -d '' dir; do
              echo "Building ${dir/overlay\//}"
              aapt p -M "$dir"/AndroidManifest.xml -S "$dir"/res/ -I /usr/local/lib/android/sdk/platforms/android-${{ env.ANDROID_API }}/android.jar --min-sdk-version ${{ env.ANDROID_API }} --target-sdk-version ${{ env.ANDROID_API }} -F "${dir/overlay\//}".apk.u
              zipalign 4 "${dir/overlay\//}".apk.u "${dir/overlay\//}".apk
              apksigner sign --key cert.pk8 --cert build/sign/testkey.x509.pem "${dir/overlay\//}".apk
              mv -v "${dir/overlay\//}".apk common/proprietary/product/overlay/
          done
          # Do not combine them into one command!
          sed -i -e 's/_%H%M%S//' build/gapps.sh
          sed -i -e '/cd $OUT/a \    find -exec touch -amt 200901010000.00 {} \\;' build/gapps.sh
          sed -i -e '/Xmx2048/d' build/gapps.sh
          sed -i -e '/Signing/a \        apksigner sign --cert $ZIP_KEY_PEM --key $GAPPS_TOP/cert.pk8 --min-sdk-version 28 /tmp/$BUILDZIP' build/gapps.sh
          sed -i -e '/apksigner/a \        cp /tmp/$BUILDZIP $OUT/$BUILDZIP' build/gapps.sh
          echo "date=$(date -u +%Y%m%d)" >> $GITHUB_ENV
          ./build/gapps.sh ${{ matrix.arch }}
          sed -i -e 's@/home/runner/work/MindTheGappsBuilder/MindTheGappsBuilder/vendor_gapps/out/@@' out/MindTheGapps-${{ matrix.androidv }}-${{ matrix.arch }}-$(date -u +%Y%m%d).zip.md5sum

      - name: Upload
        if: github.event.inputs.release != 'true'
        uses: actions/upload-artifact@v3
        with:
          name: Built_MindTheGapps-${{ matrix.androidv }}-${{ matrix.arch }}-${{ env.date }}
          path: vendor_gapps/out/*.*
          if-no-files-found: warn

      - name: Setup SSH
        if: github.event.inputs.release == 'true'
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan frs.sourceforge.net >> ~/.ssh/known_hosts
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 0600 ~/.ssh/id_ed25519

      - name: Release
        uses: softprops/action-gh-release@v1
        if: github.event.inputs.release == 'true'
        with:
          tag_name: ${{ env.date }}
          draft: false
          prerelease: false
          files: vendor_gapps/out/${{ matrix.arch }}/${{ env.date }}/*.*
